steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/data-query-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/data-query-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'data-query-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/data-query-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3001'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=3001'
      - '--set-secrets'
      - 'GROQ_API_KEY=groq-api-key:latest' 